function compute_params(type_summarypath, b_iter)

    load(sprintf('%s/summarydata.mat',type_summarypath))

    % fit each condition, per location [radial paradigm]
    try
        [params_radialout, bootparams_radialout] = ...
            fit_PF(summary_radialout, bootsummary_radialout,b_iter);
        [params_radialin, bootparams_radialin] = ...
            fit_PF(summary_radialin, bootsummary_radialin,b_iter);
        [params_tangleft, bootparams_tangleft] = ...
            fit_PF(summary_tangleft, bootsummary_tangleft,b_iter);
        [params_tangright, bootparams_tangright] = ...
            fit_PF(summary_tangright, bootsummary_tangright,b_iter);
        [params_radial, bootparams_radial] = ...
            fit_PF(summary_radial, bootsummary_radial,b_iter);
        [params_tang, bootparams_tang] = ...
            fit_PF(summary_tang, bootsummary_tang,b_iter);

        % save analyzed data
        if isfile(fullfile(type_summarypath,'analyzeddata'))
            save(fullfile(type_summarypath,'analyzeddata'), 'params_radialout',...
                'bootparams_radialout','params_radialin', 'bootparams_radialin',...
                'params_tangleft','bootparams_tangleft', ...
                'params_tangright','bootparams_tangright', 'params_radial', ...
                'bootparams_radial', 'params_tang', 'bootparams_tang', 'append')
        else
           save(fullfile(type_summarypath,'analyzeddata'), 'params_radialout',...
                'bootparams_radialout','params_radialin', 'bootparams_radialin',...
                'params_tangleft','bootparams_tangleft', ...
                'params_tangright','bootparams_tangright', 'params_radial', ...
                'bootparams_radial', 'params_tang', 'bootparams_tang') 
        end
    catch
    end
    
    % fit each condition, per location [non-radial paradigm]
    try
        [params_inclock, bootparams_inclock] = ...
            fit_PF(summary_inclock, bootsummary_inclock,b_iter);
        [params_outclock, bootparams_outclock] = ...
            fit_PF(summary_outclock, bootsummary_outclock,b_iter);
        [params_incclock, bootparams_incclock] = ...
            fit_PF(summary_incclock, bootsummary_incclock,b_iter);
        [params_outcclock, bootparams_outcclock] = ...
            fit_PF(summary_outcclock, bootsummary_outcclock,b_iter);

        % save analyzed data
        if isfile(fullfile(type_summarypath,'analyzeddata'))
            save(fullfile(type_summarypath,'analyzeddata'), 'params_inclock',...
                'bootparams_inclock','params_outclock', 'bootparams_outclock',...
                'params_incclock','bootparams_incclock', ...
                'params_outcclock','bootparams_outcclock', '-append')
        else
            save(fullfile(type_summarypath,'analyzeddata'), 'params_inclock',...
                'bootparams_inclock','params_outclock', 'bootparams_outclock',...
                'params_incclock','bootparams_incclock', ...
                'params_outcclock','bootparams_outcclock')
        end
    catch
    end
    
end