function compute_params(type_summarypath, b_iter)

    load(sprintf('%s/summarydata.mat',type_summarypath))

    % fit each condition, per location
    [params_radialout, bootparams_radialout] = ...
        fit_PF(summary_radialout, bootsummary_radialout,b_iter);
    [params_radialin, bootparams_radialin] = ...
        fit_PF(summary_radialin, bootsummary_radialin,b_iter);
    [params_tangleft, bootparams_tangleft] = ...
        fit_PF(summary_tangleft, bootsummary_tangleft,b_iter);
    [params_tangright, bootparams_tangright] = ...
        fit_PF(summary_tangright, bootsummary_tangright,b_iter);
    [params_radial, bootparams_radial] = ...
        fit_PF(summary_radial, bootsummary_radial,b_iter);
    [params_tang, bootparams_tang] = ...
        fit_PF(summary_tang, bootsummary_tang,b_iter);

    % save analyzed data
    save(fullfile(type_summarypath,'analyzeddata'), 'params_radialout',...
        'bootparams_radialout','params_radialin', 'bootparams_radialin',...
        'params_tangleft','bootparams_tangleft', ...
        'params_tangright','bootparams_tangright', 'params_radial', ...
        'bootparams_radial', 'params_tang', 'bootparams_tang')

end